### ISSUE TITLE
Link from NPM to source

### ISSUE THREAD

**Issue by ObjectiveTruth** [Ahmadposten/GIthub-slack-pullrequests-reminder#5]
Noticed on the [project page on NPM](https://www.npmjs.com/package/githubtst-slack-reminder) doesn't have a link back to this git repo.

Just took a few more clicks to look up the name/repo in google and github. I'm sure I'm not the only person to have trouble finding the repo.

Not sure how to add, but I believe you just add the repo to your package.json

See this link https://docs.npmjs.com/files/package.json#repository

**Comment by Ahmadposten** [comment]
@ObjectiveTruth Thanks for the heads up .. I updated it https://www.npmjs.com/package/github-slack-reminder
