### ISSUE TITLE
[Feature Request] Rolling the PRs into one message to post to channel

### ISSUE THREAD

**Issue by ObjectiveTruth** [Ahmadposten/GIthub-slack-pullrequests-reminder#6]
This project is really neat and very distinct from the other open source ones on the net, for example:
https://github.com/ekmartin/slack-pull-reminder
https://github.com/conorhastings/github-slack-pr-reminder
https://github.com/binaryberry/seal

I like the `mapping` feature that you have. As the other projects either write the github username in plain text, or just don't even mention it.

---
## Suggestion
What I was thinking, is a feature where all the open matching the regex PRs are posted in one message to a channel on an interval(like now), with the `@username` style mentions beside each Pull Request.

### This would be ideal because:

1. Everyone can see which PRs need to be reviewed and who's been requested to review it
    >Gentle source of embarrassment to the developer if their name keeps coming up
2. They will get a direct notification that they need to check the channel
    >It's not annoying since they can check it at their leisure. A direct message is much more invasive. And once they check, they will know that everyone else knows they need to review something.

example from a similar project:

![exampe](https://raw.githubusercontent.com/binaryberry/seal/master/images/readme/angry.png)

**Comment by Ahmadposten** [comment]
@ObjectiveTruth Cool idea .. I'll start working on that

**Comment by Ahmadposten** [comment]
@ObjectiveTruth I just implemented this feature. Would be great if you give it a try and send some feedback

**Comment by ObjectiveTruth** [comment]
@Ahmadposten Wow, sweet! I'll take a look, awesome that you took the time to do it 👍
